apiVersion: v1
data:
  tls.crt: ***************************************************************************************************************************************************************************************
  tls.key: *********************************************************************************************************************************************************************************************************************
kind: Secret
metadata:
  name: nginx-certs
type: kubernetes.io/tls
